In [21]:
import numpy as np
import pandas as pd
mynum = np.arange(20)

In [12]:
mynum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
type(mynum)

numpy.ndarray

In [18]:
blank = np.zeros((3,3))

In [20]:
for i in blank:
    print(i)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]


In [42]:
df = pd.DataFrame(blank, index = ['A','B','C'])

In [43]:
df

0    1    2
A  0.0  0.0  0.0
B  0.0  0.0  0.0
C  0.0  0.0  0.0

In [49]:
df.at['A', 0] = '1'

In [50]:
df

0    1    2    0
A  1.0  0.0  0.0    1
B  0.0  0.0  0.0  NaN
C  0.0  0.0  0.0  NaN

In [51]:
df.transpose()

A    B    C
0  1    0    0
1  0    0    0
2  0    0    0
0  1  NaN  NaN

In [56]:
df.drop(columns = '0')

0    1    2
A  1.0  0.0  0.0
B  0.0  0.0  0.0
C  0.0  0.0  0.0

In [57]:
df.drop(index='B')

0    1    2    0
A  1.0  0.0  0.0    1
C  0.0  0.0  0.0  NaN

In [58]:
df

0    1    2    0
A  1.0  0.0  0.0    1
B  0.0  0.0  0.0  NaN
C  0.0  0.0  0.0  NaN

In [59]:
df2 = df.drop(columns='0')

In [60]:
df2

0    1    2
A  1.0  0.0  0.0
B  0.0  0.0  0.0
C  0.0  0.0  0.0

In [61]:
df2.at['A', 0] = 0

In [62]:
df2

0    1    2
A  0.0  0.0  0.0
B  0.0  0.0  0.0
C  0.0  0.0  0.0

In [66]:
array = np.arange(1,21)

In [68]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
array.reshape((5,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [70]:
type(array)

numpy.ndarray